# Generated by Django 4.2.1 on 2023-05-21 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mails', '0002_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMailv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=1024, null=True)),
                ('message', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('dev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('replymail', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mails.mail')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
