# Generated by Django 4.2.1 on 2023-05-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_sentmailv1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmailv1',
            name='replymail',
        ),
    ]
