# Generated by Django 4.2 on 2023-05-10 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default=None, max_length=1024, null=True, verbose_name='EMAIL_HOST')),
                ('email_port', models.PositiveSmallIntegerField(default=587, verbose_name='EMAIL_PORT')),
                ('email_host_user', models.CharField(default=None, max_length=255, null=True, verbose_name='EMAIL_HOST_USER')),
                ('email_host_password', models.CharField(default=None, max_length=255, null=True, verbose_name='EMAIL_HOST_PASSWORD')),
                ('email_use_tls', models.BooleanField(default=True, null=True, verbose_name='EMAIL_USE_TLS')),
                ('email_use_ssl', models.BooleanField(default=False, null=True, verbose_name='EMAIL_USE_SSL')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
